export const menuItems = {
    parents: [
      {
        text: 'All Checks',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'allchecks',
      },
      { separator: true },
      {
        text: 'Online',
        icon: 'k-i-table',
        expanded: false,
        children: true,
        selected: false,
        path: 'online',
      },
      { separator: true },
      {
        text: 'Client Onboarding',
        icon: 'k-i-table',
        expanded: false,
        children: true,
        selected: false,
        path: 'onboarding',
      },
      { separator: true },
      {
        text: 'Audit Trail',
        icon: 'k-i-track-changes-accept-all',
        expanded: false,
        children: false,
        selected: false,
        path: 'audittrail',
      },
      {
        text: 'User Management',
        icon: 'k-i-user',
        expanded: false,
        children: true,
        selected: false,
        path: 'usermanagement',
      },
      { separator: true },
      {
        text: 'SPOC',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'spoc',
      },
      // { separator: true },
      // {
      //   text: 'SPOC Case Report',
      //   icon: 'k-i-folder',
      //   expanded: false,
      //   children: false,
      //   selected: false,
      //   path: 'spocCaseReport',
      // },
      { separator: true },
      {
        text: 'Bulk Upload',
        icon: 'k-i-folder',
        expanded: false,
        children: true,
        selected: false,
        path: 'bulkupload',
      },
      { separator: true },
       {
        text: 'Create Case',
        icon: 'k-i-folder',
        expanded: false,
        children: true,
        selected: false,
        path: 'createcase',
      },
      { separator: true },
      {
        text: 'Case DE XLS Config',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'casedexlsconfig',
      },
      { separator: true },
      {
        text: 'Create Case - Excel Upload',
        icon: 'k-i-folder',
        expanded: false,
        children: true,
        selected: false,
        path: 'aspose',
      },
      { separator: true },
      {
        text: 'Request Processor',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'reqprocessor',
      },
      { separator: true },
      {
        text: 'Case Details',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'casedetails',
      },
      { separator: true },
      {
        text: 'MI Fulfillment',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'fulfillment',
      },
      { separator: true },
      {
        text: 'Router Report History',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'routerReportHistory',
      },
      { separator: true },
      {
        text: 'Bot Request History',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'bothistory',
      },
      { separator: true },
      {
        text: 'Master Database',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'masterdatabase',
      },
      { separator: true },
      {
        text: 'Workflow Report',
        icon: 'k-i-aggregate-fields',
        expanded: false,
        children: false,
        selected: false,
        path: 'workflowReport',
      },
      { separator: true },
      {
        text: 'New User Management',
        icon: 'k-i-user',
        expanded: false,
        children: true,
        selected: false,
        path: 'userManagement',
      },
      { separator: true },
      {
        text: 'MRL Config',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'mrlconfig',
      }
    ],
  
    aspose: [
      {
        text: 'Case DE - XLS Upload',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'aspose/casedexls',
      },
    ],
    online: [
      {
        text: 'MIS Log',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'online/mislog',
      },
      {
        text: 'Online Case Report',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'online/onlinecasereport',
      },
      {
        text: 'Import Worldcheck Results',
        icon: 'k-i-excel',
        selected: false,
        children: false,
        level: 1,
        path: 'online/importexcel',
      },
      {
        text: 'State Master',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'masterdatabase/state_master',
      }
    ],
    usermanagement: [
      {
        text: 'Create User',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'createuser',
      },
      {
        text: 'Allocate Case',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'allocatecase',
      },
      {
        text: 'Skill management',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'skillmangagement',
      },
    ],
    bulkupload: [
      {
        text: 'Create Template',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'bulkupload/Createtemplate',
      },
      // {
      //   text: 'Template Mapping',
      //   icon: 'k-i-aggregate-fields',
      //   selected: false,
      //   children: false,
      //   level: 1,
      //   path: 'bulkupload/Templatemapping',
      // },
      {
        text: 'Bulk Tagging',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'bulkupload/Bulktagging',
      },
    ],
    userManagement: [
      {
        text: 'User Management',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'userManagement',
      },
      {
        text: 'Skill Management',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'userManagement/skillDetail',
      }
    ],
  };
  export const userMenuItems = {
    parents: [
      {
        text: 'All Checks',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'allchecks',
      },
      { separator: true },
      {
        text: 'Online',
        icon: 'k-i-table',
        expanded: false,
        children: false,
        selected: false,
        path: 'online',
      },
      { separator: true },
      {
        text: 'Client Onboarding',
        icon: 'k-i-table',
        expanded: false,
        children: false,
        selected: false,
        path: 'onboarding',
      },
      { separator: true },
      {
        text: 'Audit Trail',
        icon: 'k-i-track-changes-accept-all',
        expanded: false,
        children: false,
        selected: false,
        path: 'audittrail',
      },
      { separator: true },
      {
        text: 'SPOC',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'spoc',
      },
      { separator: true },
      {
        text: 'Bulk Upload',
        icon: 'k-i-folder',
        expanded: false,
        children: true,
        selected: false,
        path: 'bulkupload',
      },
      { separator: true },
       {
        text: 'Create Case',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'createcase',
      },
      { separator: true },
      {
        text: 'Case DE XLS Config',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'casedexlsconfig',
      },
      { separator: true },
      {
        text: 'Create Case - Excel Upload',
        icon: 'k-i-folder',
        expanded: false,
        children: true,
        selected: false,
        path: 'aspose',
      },
      { separator: true },
      {
        text: 'Request Processor',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'reqprocessor',
      },
      { separator: true },
      {
        text: 'Case Details',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'casedetails',
      },
      { separator: true },
      {
        text: 'MI Fulfillment',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'fulfillment',
      },
      { separator: true },
      {
        text: 'Router Report History',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'routerReportHistory',
      },
      { separator: true },
      {
        text: 'Bot Request History',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'bothistory',
      },
      { separator: true },
      {
        text: 'Master Database',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'masterdatabase',
      },
      { separator: true },
      {
        text: 'Workflow Report',
        icon: 'k-i-aggregate-fields',
        expanded: false,
        children: false,
        selected: false,
        path: 'workflowReport',
      },
      { separator: true },
      {
        text: 'New User Management',
        icon: 'k-i-user',
        expanded: false,
        children: true,
        selected: false,
        path: 'userManagement',
      },
      { separator: true },
      {
        text: 'MRL Config',
        icon: 'k-i-folder',
        expanded: false,
        children: false,
        selected: false,
        path: 'mrlconfig',
      }
    ],
  
    aspose: [
      {
        text: 'Case DE - XLS Upload',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'aspose/casedexls',
      },
    ],
    online: [
      {
        text: 'MIS Log',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'online/mislog',
      },
      {
        text: 'Online Case Report',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'online/onlinecasereport',
      },
      {
        text: 'Import Worldcheck Results',
        icon: 'k-i-excel',
        selected: false,
        children: false,
        level: 1,
        path: 'online/importexcel',
      },
    ],
    bulkupload: [
      {
        text: 'Create Template',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'bulkupload/Createtemplate',
      },
      {
        text: 'Template Mapping',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'bulkupload/Templatemapping',
      },
      {
        text: 'Bulk Tagging',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'bulkupload/Bulktagging',
      },
    ],
    userManagement: [
      {
        text: 'User Management',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'userManagement',
      },
      {
        text: 'Skill Management',
        icon: 'k-i-aggregate-fields',
        selected: false,
        children: false,
        level: 1,
        path: 'userManagement/skillDetail',
      }
    ],
  };